included:
  - modules/basic-pitch/ios

excluded:
  - ios
  - node_modules
  - .expo

disabled_rules:
  - cyclomatic_complexity
  - large_tuple
  - trailing_comma

line_length:
  warning: 120
  error: 160
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 700
  error: 900

file_length:
  warning: 750
  error: 1000

function_body_length:
  warning: 120
  error: 180

identifier_name:
  min_length:
    warning: 2
  excluded:
    - id
    - x
    - y
    - z
