allowBuilds:
  esbuild: true
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@tamagui/accordion@2.4.0'
  - '@tamagui/adapt@2.4.0'
  - '@tamagui/alert-dialog@2.4.0'
  - '@tamagui/animate-presence@2.4.0'
  - '@tamagui/animate@2.4.0'
  - '@tamagui/animation-helpers@2.4.0'
  - '@tamagui/animations-css@2.4.0'
  - '@tamagui/animations-motion@2.4.0'
  - '@tamagui/animations-react-native@2.4.0'
  - '@tamagui/animations-reanimated@2.4.0'
  - '@tamagui/avatar@2.4.0'
  - '@tamagui/babel-plugin@2.4.0'
  - '@tamagui/button@2.4.0'
  - '@tamagui/card@2.4.0'
  - '@tamagui/checkbox-headless@2.4.0'
  - '@tamagui/checkbox@2.4.0'
  - '@tamagui/cli-color@2.4.0'
  - '@tamagui/collapsible@2.4.0'
  - '@tamagui/collection@2.4.0'
  - '@tamagui/colors@2.4.0'
  - '@tamagui/compose-refs@2.4.0'
  - '@tamagui/config-default@2.4.0'
  - '@tamagui/config@2.4.0'
  - '@tamagui/constants@2.4.0'
  - '@tamagui/context-menu@2.4.0'
  - '@tamagui/core@2.4.0'
  - '@tamagui/create-context@2.4.0'
  - '@tamagui/create-menu@2.4.0'
  - '@tamagui/create-theme@2.4.0'
  - '@tamagui/cubic-bezier-animator@2.4.0'
  - '@tamagui/dialog@2.4.0'
  - '@tamagui/dismissable@2.4.0'
  - '@tamagui/element@2.4.0'
  - '@tamagui/elements@2.4.0'
  - '@tamagui/fake-react-native@2.4.0'
  - '@tamagui/floating@2.4.0'
  - '@tamagui/focus-guard@2.4.0'
  - '@tamagui/focus-scope@2.4.0'
  - '@tamagui/focusable@2.4.0'
  - '@tamagui/font-inter@2.4.0'
  - '@tamagui/font-silkscreen@2.4.0'
  - '@tamagui/font-size@2.4.0'
  - '@tamagui/form@2.4.0'
  - '@tamagui/generate-themes@2.4.0'
  - '@tamagui/get-button-sized@2.4.0'
  - '@tamagui/get-font-sized@2.4.0'
  - '@tamagui/get-token@2.4.0'
  - '@tamagui/group@2.4.0'
  - '@tamagui/helpers-node@2.4.0'
  - '@tamagui/helpers-tamagui@2.4.0'
  - '@tamagui/helpers@2.4.0'
  - '@tamagui/image@2.4.0'
  - '@tamagui/input@2.4.0'
  - '@tamagui/is-equal-shallow@2.4.0'
  - '@tamagui/label@2.4.0'
  - '@tamagui/linear-gradient@2.4.0'
  - '@tamagui/list-item@2.4.0'
  - '@tamagui/menu@2.4.0'
  - '@tamagui/native@2.4.0'
  - '@tamagui/normalize-css-color@2.4.0'
  - '@tamagui/polyfill-dev@2.4.0'
  - '@tamagui/popover@2.4.0'
  - '@tamagui/popper@2.4.0'
  - '@tamagui/portal@2.4.0'
  - '@tamagui/progress@2.4.0'
  - '@tamagui/proxy-worm@2.4.0'
  - '@tamagui/radio-group@2.4.0'
  - '@tamagui/radio-headless@2.4.0'
  - '@tamagui/react-native-media-driver@2.4.0'
  - '@tamagui/react-native-use-pressable@2.4.0'
  - '@tamagui/react-native-use-responder-events@2.4.0'
  - '@tamagui/react-native-web-internals@2.4.0'
  - '@tamagui/react-native-web-lite@2.4.0'
  - '@tamagui/remove-scroll@2.4.0'
  - '@tamagui/roving-focus@2.4.0'
  - '@tamagui/scroll-view@2.4.0'
  - '@tamagui/select@2.4.0'
  - '@tamagui/separator@2.4.0'
  - '@tamagui/shapes@2.4.0'
  - '@tamagui/sheet@2.4.0'
  - '@tamagui/shorthands@2.4.0'
  - '@tamagui/simple-hash@2.4.0'
  - '@tamagui/sizable-context@2.4.0'
  - '@tamagui/slider@2.4.0'
  - '@tamagui/spacer@2.4.0'
  - '@tamagui/spinner@2.4.0'
  - '@tamagui/stacks@2.4.0'
  - '@tamagui/start-transition@2.4.0'
  - '@tamagui/static-sync@2.4.0'
  - '@tamagui/static@2.4.0'
  - '@tamagui/switch-headless@2.4.0'
  - '@tamagui/switch@2.4.0'
  - '@tamagui/tabs@2.4.0'
  - '@tamagui/text@2.4.0'
  - '@tamagui/theme-builder@2.4.0'
  - '@tamagui/theme@2.4.0'
  - '@tamagui/themes@2.4.0'
  - '@tamagui/timer@2.4.0'
  - '@tamagui/toast@2.4.0'
  - '@tamagui/toggle-group@2.4.0'
  - '@tamagui/tooltip@2.4.0'
  - '@tamagui/types@2.4.0'
  - '@tamagui/use-async@2.4.0'
  - '@tamagui/use-callback-ref@2.4.0'
  - '@tamagui/use-constant@2.4.0'
  - '@tamagui/use-controllable-state@2.4.0'
  - '@tamagui/use-debounce@2.4.0'
  - '@tamagui/use-did-finish-ssr@2.4.0'
  - '@tamagui/use-direction@2.4.0'
  - '@tamagui/use-element-layout@2.4.0'
  - '@tamagui/use-escape-keydown@2.4.0'
  - '@tamagui/use-event@2.4.0'
  - '@tamagui/use-force-update@2.4.0'
  - '@tamagui/use-keyboard-visible@2.4.0'
  - '@tamagui/use-presence@2.4.0'
  - '@tamagui/use-previous@2.4.0'
  - '@tamagui/use-window-dimensions@2.4.0'
  - '@tamagui/visually-hidden@2.4.0'
  - '@tamagui/web@2.4.0'
  - '@tamagui/z-index-stack@2.4.0'
  - tamagui@2.4.0
